# Use Node.js base image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the app source code
COPY . .

# Start the app
CMD ["node", "app.js"]

# Expose port 3000
EXPOSE 3000
