# Use Node.js base image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the app source code
COPY . .

# Build the React app
RUN npm run build

# Serve the app
CMD ["npx", "serve", "build"]

# Expose port 5000
EXPOSE 5000
