apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
      - name: todo-service
        image: your-dockerhub-username/todo-service:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
