# Use Python base image
FROM python:3.9

# Create app directory
WORKDIR /usr/src/app

# Copy requirements.txt and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app source code
COPY . .

# Start the app
CMD ["python", "app.py"]

# Expose port 5002
EXPOSE 5002
